### ISSUE TITLE
Inconsistent baseforming with given locale vs. detected locale

### ISSUE THREAD

**Issue by evsheino** [jiemakel/seco-lexicalanalysis-play#1]
For some words, if analysis depth is 0, baseforming returns a different result when the locale is given compared to letting LAS detect the locale:

http://demo.seco.tkk.fi/las/baseform?depth=0&text=lohkoa&locale=fi => "lohkoa"
http://demo.seco.tkk.fi/las/baseform?depth=0&text=lohkoa => {"locale":"fi","baseform":"lohko"}

**Comment by jiemakel** [comment]
Fixed as part of latest commit (but not deployed to demo.seco.tkk.fi).
